sudo: required
services:
  - docker
before_install:
  - docker build -t sureka28/multicontainer -f ./client/Dockerfile.dev ./client
script: docker run -e CI=true sureka28/multicontainer npm run test -- --coverage
after_success:
  - docker build -t sureka28/multi-client ./client
  - docker build -t sureka28/multi-nginx ./nginx
  - docker build -t sureka28/multi-server ./server
  - docker build -t sureka28/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push sureka28/multi-client
  - docker push sureka28/multi-nginx
  - docker push sureka28/multi-server
  - docker push sureka28/multi-worker
deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-container"
  env: "MultiContainer-env"
  bucket_name: "elasticbeanstalk-us-east-2-674706550247"
  bucket_path: "multi-container"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
